server:
  port: 7070

---
environment: integration
myDevNameTree:
  devName: "Erika"
server:
  port: 3000

---
environment: test
server:
  port: 4000

---
environment: qa
server:
  port: 8975

---
environment: production
server:
  port: 8080